sim_node:
  ros__parameters:
    m: 1.0
    l: 0.5
    I: 0.25
    b: 0.05
    g: 9.81
    tau_max: 5.0
    sim_rate_hz: 200.0
    ic_mode: "downward"   # upright | near_upright | downward | random
    theta0_upright: 0.0
    theta_dot0_upright: 0.0
    theta0_near_upright: 0.2   # ~11 deg, for Week 1 Exercise B (balance)
    theta_dot0_near_upright: 0.0
    theta0_downward: 3.14159265
    theta_dot0_downward: 0.0
    theta0_random_range: [-3.14159265, 3.14159265]
    theta_dot0_random_range: [-0.5, 0.5]

controller_pid:
  ros__parameters:
    kp: 10.0
    ki: 0.0
    kd: 3.5
    tau_max: 5.0
    upright_threshold_rad: 0.2 # ~15 deg -- switch point balance <-> swing-up
    swingup_gain: 0.1             # energy-shaping gain -- TODO tune

controller_mpc:
  ros__parameters:
    horizon_steps: 50
    dt: 0.02
    tau_max: 5.0
    q_theta: 100.0
    q_theta_dot: 20.0
    r_torque: 6.0
    q_terminal_theta: 1000.0
    q_terminal_theta_dot: 100.0
